apiVersion: v1
kind: Pod
metadata:
  name: iperf-server
  namespace: benchmark
spec:
  containers:
  - name: iperf
    image: idomingc.azurecr.io/iperf3:latest
    args: ["-s"]
---
apiVersion: v1
kind: Pod
metadata:
  name: iperf-client
  namespace: benchmark
spec:
  containers:
  - name: iperf
    image: idomingc.azurecr.io/iperf3:latest
    command: ["sleep", "3600"]